# noinspection SpringBootApplicationYaml
settings:
  game-properties:
    # The delay in milliseconds between each step. Currently used when displaying each action in an encounter.
    delay-in-ms: 175
    # The speed modifier for the progress bar. The higher the value, the slower the progress. Examples: A modifier of 1
    # means that it takes 10 seconds to travel a distance of 100 km. A modifier of 0.5 means that it takes 5 seconds to
    # travel a distance of 100 km.
    speed-modifier: 0.1
  world-properties:
    size: 50
    centre: 25
    retention-zone: 2
  chunk-properties:
    size: 500
    min-placement-distance: 30
    max-guaranteed-neighbour-distance: 130
    generation-trigger-zone: 100
    density: { lower: 5, upper: 10 }
  settlement-properties:
    XS:
      area: { lower: 1, upper: 1 }
      inhabitants: { lower: 1, upper: 10 }
      amenities:
        ENTRANCE: { lower: 0, upper: 0 }
        MAIN_SQUARE: { lower: 1, upper: 1 }
        SHOP: { lower: 0, upper: 1 }
        QUEST_LOCATION: { lower: 0, upper: 2 }
        DUNGEON: { lower: 0, upper: 1 }
    S:
      area: { lower: 1, upper: 2 }
      inhabitants: { lower: 11, upper: 100 }
      amenities:
        ENTRANCE: { lower: 0, upper: 1 }
        MAIN_SQUARE: { lower: 1, upper: 1 }
        SHOP: { lower: 1, upper: 3 }
        QUEST_LOCATION: { lower: 2, upper: 5 }
        DUNGEON: { lower: 0, upper: 1 }
    M:
      area: { lower: 1, upper: 3 }
      inhabitants: { lower: 101, upper: 1000 }
      amenities:
        ENTRANCE: { lower: 1, upper: 1 }
        MAIN_SQUARE: { lower: 1, upper: 1 }
        SHOP: { lower: 3, upper: 5 }
        QUEST_LOCATION: { lower: 3, upper: 6 }
        DUNGEON: { lower: 1, upper: 2 }
    L:
      area: { lower: 2, upper: 8 }
      inhabitants: { lower: 1001, upper: 10000 }
      amenities:
        ENTRANCE: { lower: 2, upper: 3 }
        MAIN_SQUARE: { lower: 1, upper: 1 }
        SHOP: { lower: 5, upper: 9 }
        QUEST_LOCATION: { lower: 7, upper: 10 }
        DUNGEON: { lower: 2, upper: 3 }
    XL:
      area: { lower: 12, upper: 30 }
      inhabitants: { lower: 10000, upper: 250000 }
      amenities:
        ENTRANCE: { lower: 4, upper: 5 }
        MAIN_SQUARE: { lower: 1, upper: 1 }
        SHOP: { lower: 8, upper: 12 }
        QUEST_LOCATION: { lower: 9, upper: 14 }
        DUNGEON: { lower: 3, upper: 4 }
  dungeon-properties:
    encounters-per-dungeon: { lower: 1, upper: 4 }
    enemies-per-encounter: { lower: 1, upper: 3 }
    level-to-tier-divider: 10
    t1-types: GOBLIN, IMP, CYNOCEPHALY
    t2-types: SKELETON, UNDEAD, DEMON
    t3-types: ORC, TROLL, ONOCENTAUR
    t4-types: CENTICORE, POOKA, MAPUCHE, SPHINX
    t5-types: MINOTAUR, CHIMERA, CYCLOPS, HYDRA, PHOENIX
  enemy-properties:
    t1:
      damage: { multiplier: 1, minMod: 0, maxMod: 2 }
      health: { multiplier: 10, minMod: 0.7, maxMod: 1.1 }
      experience: { multiplier: 10, minMod: 0.7, maxMod: 1.1 }
      gold: { multiplier: 10, minMod: 0.7, maxMod: 1.1 }
    t2:
      damage: { multiplier: 1, minMod: 0.9, maxMod: 1.1 }
      health: { multiplier: 8, minMod: 0.8, maxMod: 1.1 }
      experience: { multiplier: 8, minMod: 0.8, maxMod: 1.1 }
      gold: { multiplier: 8, minMod: 0.8, maxMod: 1.1 }
    t3:
      damage: { multiplier: 1, minMod: 1, maxMod: 1.2 }
      health: { multiplier: 6, minMod: 0.8, maxMod: 1.2 }
      experience: { multiplier: 6, minMod: 0.8, maxMod: 1.2 }
      gold: { multiplier: 6, minMod: 0.8, maxMod: 1.2 }
    t4:
      damage: { multiplier: 1, minMod: 1, maxMod: 1.5 }
      health: { multiplier: 4, minMod: 0.8, maxMod: 1.3 }
      experience: { multiplier: 4, minMod: 0.8, maxMod: 1.3 }
      gold: { multiplier: 4, minMod: 0.8, maxMod: 1.3 }
    t5:
      damage: { multiplier: 1, minMod: 1.2, maxMod: 2 }
      health: { multiplier: 2, minMod: 0.9, maxMod: 1.3 }
      experience: { multiplier: 2, minMod: 0.9, maxMod: 1.3 }
      gold: { multiplier: 2, minMod: 0.9, maxMod: 1.3 }
  player-properties:
    starting-damage: { min: 1, max: 4 }
    experience-to-level-up: 100
    starting-gold: 100
    starting-max-health: 100